### ISSUE TITLE
Global vars not supported ?

### ISSUE THREAD

**Issue by devcrafting** [unobserved-io/espanso-gui#8]
I had a global_vars block in my "base.yml" file :

```
global_vars:
  - name: myname
    type: echo
    params:
      echo: Jon
``` 
I did a change to this file with espanso gui, it removed the global_vars block :/.
